<?php
/* @var $block Magento\Framework\View\Element\Template */
$jsLayout = json_encode([
    '#free-shipping-banner' => [
        'Magento_Ui/js/core/app' => json_decode($block->getJsLayout())
    ]
]);
?>

<div id="free-shipping-banner" data-bind="scope: 'free-shipping-banner'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    <?= $jsLayout ?>
</script>
